
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch
spec:
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        name: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:6.8.5
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx512m
           -  name: bootstrap.memory_lock
              value: "true"
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 500Mi

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  clusterIP: None
  selector:
    name: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
